### ISSUE TITLE
Error in: KitBase.jl/example/shock.jl 

### ISSUE THREAD

**Issue by rashmiraj137** [vavrines/KitBase.jl#34]
I am getting following error : 
Attaching notebook for reference: 
[shock.jl_notebook.pdf](https://github.com/vavrines/KitBase.jl/files/6610877/shock.jl_notebook.pdf)
ERROR: 
UndefVarError: ks not defined
Stacktrace:
 [1] top-level scope
   @ In[20]:1
 [2] eval
   @ ./boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094

**Comment by vavrines** [comment]
The whole example directory is a bit outdated. I'm sorry for that. 
Also some of the files aren't really examples and should go to dev directory indeed. For example, this shock.jl file in fact tries to use true particles to simulate fluid dynamics. Such method is still in development and far from being matured.
Anyway, the error is due to I added the `matter` field in the struct `Setup` probably since v0.5.
```julia
struct Setup
matter::S    
case::S   
space::S   
flux::S    
collision::S    
nSpecies::I    
interpOrder::I    
limiter::S    
boundary::S    
cfl::E    
maxTime::F
end
```
A matter needs to be defined, which now supports `gas`, `plasma` and `radiation`.

**Comment by vavrines** [comment]
The issue should be gone with the latest release.
